Repository clusterpedia-io/clusterpedia-helm, pull requests merged in 2022-10, with the labels that each got.

#3 update chart documents
  charts/clusterpedia/Chart.yaml
  charts/clusterpedia/README.md
  charts/index.yaml
Labels: size/M

#5 remove OWNER to repo root
  OWNERS
Labels: size/XS

#6 add .github
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/workflows/bot.yml
  .github/workflows/lint-chart.yaml
Labels: size/L

#11 move OWNERS to repo root
  OWNERS
Labels: size/XS

#10 Add LICENSE
  LICENSE
Labels: size/L

#9 update readme
  README.md
  charts/clusterpedia/README.md
Labels: size/M

#8 add publish charts workflow
  .github/workflows/publish.yml
Labels: size/M

#12 optimize helm crds
  charts/clusterpedia/Chart.yaml
  charts/clusterpedia/README.md
  charts/clusterpedia/_crds/cluster.clusterpedia.io_clustersyncresources.yaml
  charts/clusterpedia/_crds/cluster.clusterpedia.io_pediaclusters.yaml
  charts/clusterpedia/_crds/policy.clusterpedia.io_clusterimportpolicies.yaml
  charts/clusterpedia/_crds/policy.clusterpedia.io_pediaclusterlifecycles.yaml
  charts/clusterpedia/templates/_helpers.tpl
  charts/clusterpedia/templates/customresourcedefinitions.yaml
  charts/clusterpedia/templates/pre-hook-job.yaml
  charts/clusterpedia/templates/pre-hook-rbac.yaml
  charts/clusterpedia/templates/pre-hook-serviceaccount.yaml
  charts/clusterpedia/values.yaml
Labels: size/L, lgtm

#14 optimize hook job image
  charts/clusterpedia/Chart.yaml
  charts/clusterpedia/templates/_helpers.tpl
Labels: size/XS, lgtm

#15 set helm version of publish action
  .github/workflows/publish.yml
Labels: size/XS
