Repository clusterpedia-io/clusterpedia-helm, pull requests merged in 2022-12, with the labels that each got.

#19 Update clusterpedia image to v0.5.2
  charts/clusterpedia/Chart.yaml
  charts/clusterpedia/README.md
  charts/clusterpedia/values.yaml
Labels: size/S

#23 clusterpedia-core: support storage layer configuration
  charts/clusterpedia-core/templates/_helpers.tpl
  charts/clusterpedia-core/templates/_storage_override.yaml
  charts/clusterpedia-core/templates/apiserver-deployment.yaml
  charts/clusterpedia-core/templates/clustersynchro-manager-deployment.yaml
  charts/clusterpedia-core/templates/storage-configmap.yaml
  charts/clusterpedia-core/values.yaml
Labels: size/L

#25 clusterpedia-core: support configuration of storage plugin image
  charts/clusterpedia-core/templates/_helpers.tpl
  charts/clusterpedia-core/templates/apiserver-deployment.yaml
  charts/clusterpedia-core/templates/clustersynchro-manager-deployment.yaml
  charts/clusterpedia-core/values.yaml
Labels: size/L

#26 clusterpedia-core: update version to 0.1.0
  charts/clusterpedia-core/Chart.yaml
Labels: size/XS

#29 clusterpedia-core: update version to 0.1.1
  charts/clusterpedia-core/Chart.yaml
  charts/clusterpedia-mysql/Chart.yaml
Labels: size/XS

#30 clusterpedia: bump image tag to v0.6.0
  charts/clusterpedia/Chart.yaml
  charts/clusterpedia/templates/clustersynchro-manager-deployment.yaml
  charts/clusterpedia/values.yaml
Labels: size/M, lgtm

#31 clusterpedia-mysql: update Chart.lock
  charts/clusterpedia-mysql/Chart.lock
Labels: size/XS

#32 fix publish workflow
  .github/workflows/publish.yml
Labels: size/XS
